name: genesix
description: Secure and intuitive cross-platform wallet for the XELIS network.
publish_to: 'none'

version: 0.1.3

environment:
  sdk: ^3.11.0

dependencies:
  path: any
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  change_app_package_name: ^1.5.0
  flutter_form_builder: ^10.3.0+2
  flutter_riverpod: ^3.2.1
  form_builder_validators: ^11.3.0
  freezed_annotation: ^3.1.0
  go_router: ^17.1.0
  intl: any
  json_annotation: ^4.11.0
  logging: ^1.3.0
  path_provider: ^2.1.5
  riverpod_annotation: ^4.0.2
  shared_preferences: ^2.5.4
  xelis_dart_sdk: ^0.30.12
  loader_overlay: ^5.0.0
  pretty_qr_code: ^3.6.0
  mobile_scanner: ^7.2.0
  flutter_native_splash: ^2.4.7
  window_manager: ^0.5.1
  country_flags: ^4.1.2
  package_info_plus: ^9.0.0
  file_picker: ^10.3.10
  icons_launcher: ^3.0.3
  url_launcher: ^6.3.2
  localstorage: ^6.0.0
  talker_flutter: ^5.1.13
  talker_riverpod_logger: ^5.1.13
  group_button: ^5.3.4
  http: ^1.6.0
  google_fonts: ^8.0.2
  io: ^1.0.5
  flutter_secure_storage: ^10.0.0
  local_auth: ^3.0.0
  web: ^1.1.1
  infinite_scroll_pagination: ^5.1.1
  forui: ^0.19.0
  animations: ^2.1.1
  jovial_svg: ^1.1.29
  fl_chart: ^1.1.1
  skeletonizer: ^2.1.3
  recase: ^4.1.0
  web_socket_channel: ^3.0.3
  encrypt: ^5.0.3

  flutter_rust_bridge: 2.11.1
  rust_builder:
    path: rust_builder
  flutter_hashicon:
    git: https://github.com/xelis-project/flutter-hashicon.git

dev_dependencies:
  build_runner: ^2.11.1
  go_router_builder: ^4.2.0
  flutter_lints: ^6.0.0
  freezed: ^3.2.5
  json_serializable: ^6.13.0
  riverpod_generator: ^4.0.3
  riverpod_lint: ^3.1.3
  msix: ^3.16.13
  #  flutter_test:
  #    sdk: flutter
  #  integration_test:
  #    sdk: flutter


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/png/circle/green_background_black_logo.png
    - assets/genesix/svg/genesix-wallet-one-line_white.svg
    - assets/genesix/svg/genesix-wallet-one-line_black.svg

msix_config:
  display_name: Genesix Wallet
  publisher_display_name: XELIS
  logo_path: assets/icons/png/circle/green_background_black_logo.png
