name: genesix
description: Secure and intuitive cross-platform wallet for the XELIS network.
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  path: any
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  change_app_package_name: ^1.5.0
  flutter_form_builder: ^10.2.0
  flutter_riverpod: ^2.6.1
  form_builder_validators: ^11.2.0
  freezed_annotation: ^3.1.0
  go_router: ^16.2.4
  intl: any
  json_annotation: ^4.9.0
  logging: ^1.3.0
  path_provider: ^2.1.5
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  xelis_dart_sdk: ^0.29.0
  loader_overlay: ^5.0.0
  pretty_qr_code: ^3.5.0
  flutter_native_splash: ^2.4.6
  window_manager: ^0.5.1
  country_flags: ^4.0.1
  package_info_plus: ^9.0.0
  file_picker: ^10.3.3
  icons_launcher: ^3.0.3
  url_launcher: ^6.3.2
  localstorage: ^6.0.0
  talker_flutter: ^5.0.1
  talker_riverpod_logger: ^5.0.1
  group_button: ^5.3.4
  http: ^1.5.0
  google_fonts: ^6.3.2
  io: ^1.0.5
  flutter_secure_storage: ^9.2.4
  local_auth: ^2.3.0
  web: ^1.1.1
  infinite_scroll_pagination: ^5.1.1
  forui: ^0.15.1
  animations: ^2.0.11
  jovial_svg: ^1.1.28
  fl_chart: ^1.1.1
  skeletonizer: ^2.1.0+1
  #  flutter_hooks: ^0.20.5
  #  hooks_riverpod: ^2.4.10
  #  flutter_animate: ^4.5.0
  #  workmanager: ^0.5.2
  #  transparent_image: ^2.0.1
  #  uuid: ^4.5.1

  flutter_rust_bridge: 2.11.1
  rust_builder:
    path: rust_builder
  flutter_hashicon:
    git: https://github.com/xelis-project/flutter-hashicon.git

dev_dependencies:
  build_runner: ^2.5.4
  go_router_builder: ^3.0.0
  flutter_lints: ^6.0.0
  custom_lint: ^0.7.6
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  msix: ^3.16.12
  #  flutter_test:
  #    sdk: flutter
  #  integration_test:
  #    sdk: flutter


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/png/circle/green_background_black_logo.png
    - assets/genesix/svg/genesix-wallet-one-line_white.svg
    - assets/genesix/svg/genesix-wallet-one-line_black.svg

msix_config:
  display_name: Genesix Wallet
  publisher_display_name: XELIS
  logo_path: assets/icons/png/circle/green_background_black_logo.png
